
##### SETUP #####

setup:
  version: "1.0.11" # DO NOT CHANGE

  # When setting up your bot, enter the bots token and your server ID below
  token: "ODUzOTc5NDc4MjA2OTcxOTM0.YMdQXQ.3GW6wOQQdU8rC2dgG_vvkGMZnys"
  serverID: "848020471370088458"


##### SETTINGS #####

colour: "FF0062"
prefix: "="

serverName: "LexCraft"
botName: "LexCraft"
footer: "Â© LexCraft | Owned by LexCraft | Developed by Facu"

statusMessage: "-help | mc.lexcraft.club"
    
disabledCommands: [""]

inviteSystem: "on"


##### CORE #####

core:
  fun: "on"
  moderation: "on"
  tickets: "on"
  utilities: "on"
  giveaways: "on"
  economy: "on"
  levels: "on"
  music: "on"


##### WELCOME #####

autoRoles: ["ã€Œâ›¹ï¸ã€Usuariosã€Œâ›¹ï¸ã€"]

joinLeaveMessage: "on"
joinLeaveChannel: "ã€ŒğŸ‘‹ã€entradas"

welcomeMsgLine1: "Thanks For Joining Us"
welcomeMsgLine2: "From the LexCraft Network"

leaveMsgLine1: "Hope your enjoyed your stay"
leaveMsgLine2: "From the LexCraft Network"

verificationSystem: "on"
verificationRole: "ã€Œâ›¹ï¸ã€Usuariosã€Œâ›¹ï¸ã€"
verificationChannel: "ã€ŒğŸ‘‹ã€verificacion"


##### ROLES #####

mutedRole: "Muteds"
defaultRole: "ã€Œâ›¹ï¸ã€Usuariosã€Œâ›¹ï¸ã€"
staffRole: "ã€Œâš’ï¸ã€Staff Teamã€Œâš’ï¸ã€"
managementRole: "ã€ŒğŸ”±ã€Managerã€ŒğŸ”±ã€"


##### CHANNEL MANAGEMENT #####

logChannel: "logs"
suggestionChannel: "suggestions"
reportChannel: "logs"
bugChannel: "logs"


##### TICKETS #####

ticketSystem: "on"
ticketCategory: "= Soporte"


##### APPLICATION #####

applicationSystem: "off"
applicationCategory: "= Soporte"
applicationChannel: "logs"
applicationPosition: "Moderator"
applicationQuestions:  [
  "Question 1",
  "Question 2",
  "Question 3",
  "Question 4",
  "Question 5",
  "Question 6",
  "Question 7",
  "Question 8",
  "Question 9",
  "Question 10",
  "Question 11"
]


#### Giveaways ####

giveaways:
  botsCanWin: false
  ignoreIfHasPermission: []
  embedColor: "#FF0062"
  embedColorEnd: "#FF0062"
  reaction: "ğŸ‰"
messages:
  giveaway: "ğŸ‰ğŸ‰ **GIVEAWAY** ğŸ‰ğŸ‰"
  giveawayEnded: "ğŸ‰ğŸ‰ **GIVEAWAY ENDED** ğŸ‰ğŸ‰"
  timeRemaining: "Time remaining: **{duration}**!"
  inviteToParticipate: "React with ğŸ‰ to participate!"
  winMessage: "Congratulations, {winners}! You won **{prize}**!"
  embedFooter: "LexCraft Giveaways"
  noWinner: "Giveaway cancelled, no valid participations."
  winners: "winner(s)"
  endedAt: "End at"
  rerollMessage: "ğŸ‰ New winner(s) : {winners}! Congratulations!"


##### Economy #####

workCooldown: 300000


##### LEVEL SYSTEM #####

levelSystem: "on"
levelChannel: "current"
levelCoolDown: 30000
levelMaxPoints: 15


##### LINKS #####

social:
  facebook: ""
  twitter: ""
  instagram: ""
  youtube: ""
  twitch: ""

online:
  website: "www.lexcraft.club"
  forums: "foro.lexcraft.club"


##### FILTERS #####

# s - staff role
# m - management role

swearFilter: "on"
swearWords: ["fuck","shit","piss","dick","fucker","cock","cunt","bitch","whore","arse",
            "bastard","wanker","bullshit","nigger","slut","choad"]
swearBypass: ["s","m"]

inviteFilter: "on"
inviteBypass: ["s","m"]


##### PERMISSIONS #####

# s - staff role
# m - management role

permissions:
  announce: "m"
  addrole: "m"
  removerole: "m"

  delete: "m"
  forcedelete: "m"
  lower: "m"
  raise: "m"
  add: "m"
  remove: "m"
  notice: "m"

  ban: "s"
  clear: "s"
  kick: "s"
  lockdown: "m"
  mute: "s"
  say: "m"
  shout: "m"
  speak: "m"
  slowmode: "m"
  tempmute: "s"
  unban: "s"
  unmute: "s"
  warn: "s"

  
##### GIFS #####

slap: ["https://media.giphy.com/media/TA9NZjiqCIOTC/giphy.gif",
       "https://media0.giphy.com/media/9j6ZRLTLPxjpu/source.gif",
       "https://giphy.com/gifs/hulu-mindy-kaling-the-project-lahiri-l3vRb8wtvRtW9mOk0",
       "https://giphy.com/gifs/bojack-horseman-todd-chavez-face-slap-l2YOqzhYD066fAd56",
       "https://giphy.com/gifs/lol-jimmy-fallon-reaction-gifs-Hz3YLyGYc15Oo",
       "https://giphy.com/gifs/ratboys-l0Iy4KUJ0Q4prROOQ"]
    
hug: ["https://i.pinimg.com/originals/0a/16/52/0a1652de311806ce55820a7115993853.gif",
      "https://media.tenor.com/images/42a6820297796b572c36aeb9d86ef684/tenor.gif",
      "https://tenor.com/view/hugging-hug-gif-10592461",
      "https://tenor.com/view/warm-hug-gif-10592083",
      "https://tenor.com/view/wyatt-logan-timeless-matt-lanter-lucy-preston-abigail-spencer-gif-12254044",
      "https://tenor.com/view/big-hero6-baymax-feel-better-hug-hugging-gif-4782499",
      "https://tenor.com/view/hug-peachcat-cat-cute-gif-13985247",
      "https://tenor.com/view/cuddle-party-finding-dory-disney-hug-gif-7278312",
      "https://tenor.com/view/frozen-anna-elsa-hug-hugging-gif-4911454"]
